// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl2oTLhRPIsT_mCw4VWx7c_nSNzA2QdTA',
    appId: '1:324991063451:web:1769956a4dc103144fbd3e',
    messagingSenderId: '324991063451',
    projectId: 'zaloclone-bc390',
    authDomain: 'zaloclone-bc390.firebaseapp.com',
    databaseURL:
        'https://zaloclone-bc390-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zaloclone-bc390.appspot.com',
    measurementId: 'G-GPTQETPXQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPfXhUKidi0nmFjUgkBCZKWUo-2exssE8',
    appId: '1:324991063451:android:9089beada7f676234fbd3e',
    messagingSenderId: '324991063451',
    projectId: 'zaloclone-bc390',
    databaseURL:
        'https://zaloclone-bc390-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zaloclone-bc390.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_FadxYNe0HFsxcdm05AM3cu-cTNOAuUI',
    appId: '1:324991063451:ios:368abe1883d974b94fbd3e',
    messagingSenderId: '324991063451',
    projectId: 'zaloclone-bc390',
    databaseURL:
        'https://zaloclone-bc390-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zaloclone-bc390.appspot.com',
    iosClientId:
        '324991063451-10nmtfddb9b9kiaubhvcqrn9c6f4ie93.apps.googleusercontent.com',
    iosBundleId: 'com.testing.zalo',
  );
}
